apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: trigger-template
spec:
  params:
    - name: repository
      description: the git repository
    - name: revision
      description: the git repo branch 
    - name: apikey
      description: the api key
  resourcetemplates:
    # CD secret to provide API_KEY to access toolchain information
    - apiVersion: v1
      kind: Secret
      metadata:
        name: cd-secret
      type: Opaque
      stringData:
        apikey: $(params.apikey)
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
          name: activitytracker-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
          - name: repository
            value: $(params.repository)
          - name: revision
            value: $(params.revision)
          - name: apikey
            value: $(params.apikey)

---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: trigger-binding
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: event-listener
spec:
  triggers:
    - binding:
        name: trigger-binding
      template:
        name: trigger-template
